### PR TITLE
Allow seek when writing

### PR DESCRIPTION
**Pull request by jonmclean**
The standard Rust File struct allows seeking when writing to files so VFS should as well.  VFS already allows seek when reading files.

This is useful when testing code that reads & writes sections of a file.

### CODE REVIEW

**Comment by manuel-woelker** [comment]
Thanks for the PR! Great addition to cover more use cases.

**Comment by jonmclean** [comment]
My team looks forward to using this after this changes makes it to crates.io.

Thank you for the quick response to the pr.

**Comment by manuel-woelker** [comment]
Great to hear, I'll try to cut a release next weekend.

**Comment by manuel-woelker** [comment]
Release 0.12.0 is out and should be available on crates.io. Let me know if you have any issues!

**Comment by jonmclean** [comment]
Thank you very much.  I have updated to the new version.

**Pull request merged**
